name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ${{env.working-directory}}

      - name: Lint code
        run: |
          pip install flake8
          flake8 --exclude=__init__.py

